# Generated by Django 5.2.4 on 2025-07-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clima',
            name='icono',
            field=models.CharField(default='01d', max_length=10),
            preserve_default=False,
        ),
    ]
